<a href="https://colab.research.google.com/github/alex-njuguna/pytorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Introduction to tensors

## Creating tensors

### Scalar

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Check the dimensions of the scalar tensor
scalar.ndim

0

In [4]:
# Get the number within the tensor to a python integer using item()
scalar.item()

7

### Vector

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Check the nnumber of dimensions of a vector with ndim
vector.ndim

1

In [7]:
# Check the shape of a vector
vector.shape

torch.Size([2])

### Matrix

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Check number of dimensions
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [13]:
# Check shape of a tensor
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors

In [15]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0756, 0.8041, 0.3294, 0.5981],
         [0.1082, 0.1464, 0.8585, 0.0835],
         [0.9330, 0.5101, 0.2188, 0.8576]]),
 torch.float32)

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
"""Filling tensors with zeroes - this happens when you want the model not to run them"""

In [20]:
# Create a tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
# Create a tensor of ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [ ]:
"""Use torch.arange(start, stop, step), using range() is deprecated and may output an error"""

In [24]:
# zero_to_ten_deprecated = torch.range(0, 10)
# zero_to_ten_deprecated
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To have a tensor of similar shape like a previous tensor with **zeros** or **ones** you can use **torch.zeros_like(input)** and **torch.ones_like(input)** which return a tensor filled with zeros or ones respectively

In [26]:
# Create a tensor of zeros similar to a previous tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [28]:
# Default datatype of tensor is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to none, whic is float32 or whatever datatype was passed,
                               device=None, # defaults to none, which uses the the default tensor type,
                               requires_grad=False) #If true operations perfomed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
# Create a tensor with dtype=torch.float_16
float_16_tensor = torch.tensor([3.0, 9.0, 7.8],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

# Getting information from tensors

In [30]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find details about the above tensor
print(some_tensor)
print(f"shape of the tensor: {some_tensor.shape}")
print(f"Data type of the tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # defaults to cpu

tensor([[0.5294, 0.6879, 0.6389, 0.4836],
        [0.4644, 0.6100, 0.5182, 0.0836],
        [0.2640, 0.4117, 0.6885, 0.1602]])
shape of the tensor: torch.Size([3, 4])
Data type of the tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors(tensor operations)

operations - addition, substraction, multiplication, division and Matrix multiplication

## Basic operations

In [31]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# tensors don't change unless they are reassigned
tensor

tensor([1, 2, 3])

In [34]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [35]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch also has built-in functions like **torch.mul()** and **torch.add()** to perform basic operations

In [37]:
# Can also use torch functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
# multiplying two tensors with an operator
print(f"{tensor} * {tensor} equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) equals: tensor([1, 4, 9])


## Matrix multiplication

use **torch.matmul()** method

__Rules__
- The inner dimensions must match
- The resulting matrix has the shape of the outer dimensions
- @ in python is the symbol of matrix multiplication

1. Elemen-wise multiplication [1x1, 2x2, 3x3] = [1, 4, 9]
2. Matrix Multiplication [1X1 + 2X2 + 3x3] = [13]

In [40]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [41]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [42]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)