<a href="https://colab.research.google.com/github/alex-njuguna/pytorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Introduction to tensors

## Creating tensors

### Scalar

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Check the dimensions of the scalar tensor
scalar.ndim

0

In [ ]:
# Get the number within the tensor to a python integer using item()
scalar.item()

7

### Vector

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Check the nnumber of dimensions of a vector with ndim
vector.ndim

1

In [ ]:
# Check the shape of a vector
vector.shape

torch.Size([2])

### Matrix

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
# Check number of dimensions
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

### Tensor

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [ ]:
# Check shape of a tensor
TENSOR.shape

torch.Size([1, 3, 3])

## Random tensors

In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0756, 0.8041, 0.3294, 0.5981],
         [0.1082, 0.1464, 0.8585, 0.0835],
         [0.9330, 0.5101, 0.2188, 0.8576]]),
 torch.float32)

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

## Zeros and ones

In [ ]:
"""Filling tensors with zeroes - this happens when you want the model not to run them"""

In [ ]:
# Create a tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
# Create a tensor of ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

## Creating a range and tensors like

In [ ]:
"""Use torch.arange(start, stop, step), using range() is deprecated and may output an error"""

In [ ]:
# zero_to_ten_deprecated = torch.range(0, 10)
# zero_to_ten_deprecated
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To have a tensor of similar shape like a previous tensor with **zeros** or **ones** you can use **torch.zeros_like(input)** and **torch.ones_like(input)** which return a tensor filled with zeros or ones respectively

In [ ]:
# Create a tensor of zeros similar to a previous tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

In [ ]:
# Default datatype of tensor is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to none, whic is float32 or whatever datatype was passed,
                               device=None, # defaults to none, which uses the the default tensor type,
                               requires_grad=False) #If true operations perfomed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
# Create a tensor with dtype=torch.float_16
float_16_tensor = torch.tensor([3.0, 9.0, 7.8],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16

# Getting information from tensors

In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)

# Find details about the above tensor
print(some_tensor)
print(f"shape of the tensor: {some_tensor.shape}")
print(f"Data type of the tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # defaults to cpu

tensor([[0.5294, 0.6879, 0.6389, 0.4836],
        [0.4644, 0.6100, 0.5182, 0.0836],
        [0.2640, 0.4117, 0.6885, 0.1602]])
shape of the tensor: torch.Size([3, 4])
Data type of the tensor: torch.float32
Device tensor is stored on: cpu


# Manipulating tensors(tensor operations)

operations - addition, substraction, multiplication, division and Matrix multiplication

## Basic operations

In [ ]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# tensors don't change unless they are reassigned
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

PyTorch also has built-in functions like **torch.mul()** and **torch.add()** to perform basic operations

In [ ]:
# Can also use torch functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# multiplying two tensors with an operator
print(f"{tensor} * {tensor} equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) equals: tensor([1, 4, 9])


## Matrix multiplication

use **torch.matmul()** method

__Rules__
- The inner dimensions must match
- The resulting matrix has the shape of the outer dimensions
- @ in python is the symbol of matrix multiplication

1. Elemen-wise multiplication [1x1, 2x2, 3x3] = [1, 4, 9]
2. Matrix Multiplication [1X1 + 2X2 + 3x3] = [13]

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor

tensor([1, 2, 3])

In [ ]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

# One of the most common errors in deep learning(shape errors)

In [ ]:
# shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)
# torch.matmul(tensor_A, tensor_B)

we can make matrix multiplication between tensor_A and tensor_B possible through making their inner dimensions math. i.e. using **transpose**(_switch the dimensions of a given tensor_)

**Perform tansponses with pytorch either:**
- `torch.transpose(input, dim0, dim1)` - where `input` is the desired tensor to transpose and `dim0` and `dim1` are the dimensions to be swapped.
- `tensor.T` - where `tensor` is the desired tensor to transpose

In [ ]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [ ]:
# view tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [ ]:
# the torch.matmul(tensor_A, tensor_B) works when tensor_B is transposed
print(f"Original shapes:\ntensor_A: {tensor_A.shape}\ntensor_B: {tensor_B.shape}")
print(f"New shapes:\ntensor_A: {tensor_A.shape}\ntensor_B.T: {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape}--->")
print()
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\noutput shape:\n{output.shape}")

Original shapes:
tensor_A: torch.Size([3, 2])
tensor_B: torch.Size([3, 2])
New shapes:
tensor_A: torch.Size([3, 2])
tensor_B.T: torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3])--->

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

output shape:
torch.Size([3, 3])


In [ ]:
# torch.mm is a shortcut for torch.matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

## Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum: {x.min()}")
print(f"Maximun: {x.max()}")
print(f"Average: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximun: 90
Average: 45.0
Sum: 450


## Positional min/max

find the position or index of a tennsor  where the max or min occurs using **torch.argmax()** and **torch.argmin()** respectively

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


## Change tensor data type

The data type of a tensor can be changed using **torch.Tensor.type(dtype=None)** where *dtype* is the data type you would like to use

In [ ]:
# Create a tensor and check its data type
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [ ]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16.dtype, tensor_float16

(torch.float16,
 tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16))

In [ ]:
# Create an int8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, stacking, squeezing and unsqueezing

Reshaping or changing the dimensions of tensors is often needed without changing the values inside the tensors.
Some popular methods are:
1. torch.reshape(input, shape) - Reshapes input to shape *(if compatible)*, can also use `torch.Tensor.reshape()`
2. Tensor.view(shape) - Returns a view of the original tensor in a different `shape` but the data is not altered.
3. torch.stack(tensors, dim=0) - Concantenates a sequence of tensors along a new dimension `(dim)`, all tensors have to be of a smilar size.
4. torch.squeeze(input) - Squeezes `input` to remove all the dimensions with the value 1.
5. torch.unsqueeze(input, dim) - Return `input` with a dimension of 1 added at `dim`.
6. torch.permute(input, dims) - Returns a view of the original input with its dimensions permutted(rearranged) to `dims`.

In [ ]:
# create a tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

# Indexing (selecting data from tensors)

In [2]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [4]:
# Indexing bracket by bracket
print(f"First square bracket:\n {x[0]}")
print(f"Second square braket:\n {x[0][0]}")
print(f"Third square bracket:\n {x[0][0][0]}")

First square bracket:
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square braket:
 tensor([1, 2, 3])
Third square bracket:
 1


In [5]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [6]:
# Get all values of 0th & 1st dimesions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [14]:
# Create a tensor 3D of shape (2-blocks, 3-rows, 4-columns)
tensor = torch.arange(1, 25).reshape(2, 3, 4)
tensor


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

## Basic indexing

You can access tensor elements using three indices: [block, row, column]

### Accessing single elements

In [16]:
# Access the element at block 1, row 2, column 3
element = tensor[1, 2, 3]
element

tensor(24)

### Accessing a specific row

In [17]:
# Access the second row of the the first block
row = tensor[0, 1]
row

tensor([5, 6, 7, 8])

## Slicing

### Accessing a sub-tensor

In [18]:
# Access rows from both blocks at index 1
sub_tensor = tensor[0:2, 1, :]
sub_tensor

tensor([[ 5,  6,  7,  8],
        [17, 18, 19, 20]])

### Accessing all rows in a block

In [19]:
# Access the first block
block = tensor[0]
block

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

## Advanced Indexing

### Boolean indexing

Create a mask to filter values

In [20]:
# Creates a mask for values greater than 15
mask = tensor > 15
filtered = tensor[mask]
filtered

tensor([16, 17, 18, 19, 20, 21, 22, 23, 24])

### Indexing with lists

Also possible to use a list of indices to access specific blocks, rows or columns

In [21]:
indices = [0, 1]
selected_blocks = tensor[indices] # select both blocks
selected_blocks

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])

## Modifying tensors

### Changing a specific element

In [22]:
# Change the value of block 1, row 2 column 3 to 100
tensor[1, 2, 3] = 100
tensor

tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ 13,  14,  15,  16],
         [ 17,  18,  19,  20],
         [ 21,  22,  23, 100]]])

### Changing the entire row

In [23]:
# Modify the second row of the first block
tensor[0, 1] = torch.tensor([99, 98, 97, 96])
tensor

tensor([[[  1,   2,   3,   4],
         [ 99,  98,  97,  96],
         [  9,  10,  11,  12]],

        [[ 13,  14,  15,  16],
         [ 17,  18,  19,  20],
         [ 21,  22,  23, 100]]])

## Multi-Dimensional Indexing

### Accessing all columns for specific rows

In [24]:
# Accesses the second row across all blocks
rows = tensor[:, 1, :]
rows

tensor([[99, 98, 97, 96],
        [17, 18, 19, 20]])

# PyTorch tensors & NumPy

Two main methods used for numpy to pytorch and back are:
- `torch.from_numpy(ndarray)` - numpy aray -> pytorch tensor
- `torch.Tensor.numpy()` - pytorch tensor -> numpy array

In [25]:
# numpy array to tensor
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [26]:
# change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [30]:
# Tensor to numpy array
tensor = torch.ones(7) # Create a tensor of ones with dtype float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [31]:
# change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

- To control randomness thus enehance reproducibility, i.e.get results of similar flavour from randomness, `torch.manual_seed(seed)` is used.
- `seed` is an integer e.g. 7 that flavours the randomness

In [34]:
import random

RANDOM_SEED = 7
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_c = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called, Otherwise tensor_d would be different
# to tensor_c
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_d = torch.rand(3, 4)

print(f"Tensor c:\n{random_tensor_c}")
print(f"Tensor d:\n{random_tensor_d}")
print(f"\nDoes Tensor c equal Tensor d? (anywhere)?\n")
random_tensor_c == random_tensor_d

Tensor c:
tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])
Tensor d:
tensor([[0.5349, 0.1988, 0.6592, 0.6569],
        [0.2328, 0.4251, 0.2071, 0.6297],
        [0.3653, 0.8513, 0.8549, 0.5509]])

Does Tensor c equal Tensor d? (anywhere)?



tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])