<a href="https://colab.research.google.com/github/alex-njuguna/pytorch/blob/main/pytorch_introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [18]:
torch.__version__

'2.5.0+cu121'

In [3]:
tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 0.0723, -0.8538,  0.6163, -0.0968],
        [ 1.4756, -1.1573, -0.2213, -0.1207],
        [-0.6589, -2.2417,  2.3150,  0.7445]])

In [4]:
print(type(tensor_2d))

<class 'torch.Tensor'>


# Tensor operations

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Reshape and view
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
# Reshpae if we dont know the number of items using -1
my_torch2 = torch.arange(21)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])

In [15]:
my_torch2 = my_torch2.reshape(3, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]])

In [16]:
# using view
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
my_torch4 = my_torch3.view(2, -1)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])