<a href="https://colab.research.google.com/github/alex-njuguna/pytorch/blob/main/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

# Creating tensors

## Scalar

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Check the dimensions of the scalar tensor
scalar.ndim

0

In [4]:
# Get the number within the tensor to a python integer using item()
scalar.item()

7

## Vector

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Check the nnumber of dimensions of a vector with ndim
vector.ndim

1

In [7]:
# Check the shape of a vector
vector.shape

torch.Size([2])

## Matrix

In [8]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Check number of dimensions
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

## Tensor

In [11]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [13]:
# Check shape of a tensor
TENSOR.shape

torch.Size([1, 3, 3])

# Random tensors

In [15]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.0756, 0.8041, 0.3294, 0.5981],
         [0.1082, 0.1464, 0.8585, 0.0835],
         [0.9330, 0.5101, 0.2188, 0.8576]]),
 torch.float32)

In [18]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

# Zeros and ones

In [ ]:
"""Filling tensors with zeroes - this happens when you want the model not to run them"""

In [20]:
# Create a tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
# Create a tensor of ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

# Creating a range and tensors like

In [ ]:
"""Use torch.arange(start, stop, step), using range() is deprecated and may output an error"""

In [24]:
# zero_to_ten_deprecated = torch.range(0, 10)
# zero_to_ten_deprecated
zero_to_ten = torch.arange(0, 10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To have a tensor of similar shape like a previous tensor with **zeros** or **ones** you can use **torch.zeros_like(input)** and **torch.ones_like(input)** which return a tensor filled with zeros or ones respectively

In [26]:
# Create a tensor of zeros similar to a previous tensor
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

In [28]:
# Default datatype of tensor is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to none, whic is float32 or whatever datatype was passed,
                               device=None, # defaults to none, which uses the the default tensor type,
                               requires_grad=False) #If true operations perfomed on the tensor are recorded
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [29]:
# Create a tensor with dtype=torch.float_16
float_16_tensor = torch.tensor([3.0, 9.0, 7.8],
                               dtype=torch.float16)
float_16_tensor.dtype

torch.float16